# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: election_grpc.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13\x65lection_grpc.proto\x12\relection_grpc\"\x07\n\x05\x45mpty\"%\n\x13GetElectionResponse\x12\x0e\n\x06status\x18\x01 \x01(\x05\x32\\\n\x0f\x45lectionService\x12I\n\x0bGetElection\x12\x14.election_grpc.Empty\x1a\".election_grpc.GetElectionResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'election_grpc_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_EMPTY']._serialized_start=38
  _globals['_EMPTY']._serialized_end=45
  _globals['_GETELECTIONRESPONSE']._serialized_start=47
  _globals['_GETELECTIONRESPONSE']._serialized_end=84
  _globals['_ELECTIONSERVICE']._serialized_start=86
  _globals['_ELECTIONSERVICE']._serialized_end=178
# @@protoc_insertion_point(module_scope)
